'use client'

import { useState } from 'react'
import { Check, Download, FileText, MessageCircle, Settings2, Share2, Sparkles, Target } from 'lucide-react'
import { JourneyState, currency, exportPlanText, planAssumptions, planOpportunities, planRisks, remainingGoal, totalContribution } from '@/lib/ocbc-journey'

type Props = { journey: JourneyState; onUpdate: (next: Partial<JourneyState>) => void; onNavigate?: (view: 'hub' | 'report') => void }
const tabs = ['Overview', 'Timeline', 'Categories', 'Actions'] as const

export function FinancialReport({ journey, onUpdate }: Props) {
  const [tab, setTab] = useState<(typeof tabs)[number]>('Overview')
  const [shared, setShared] = useState(false)
  const [discussed, setDiscussed] = useState(false)
  const [variance, setVariance] = useState(false)
  const plan = journey.plan
  const generate = () => onUpdate({ reportGenerated: true })
  const exportReport = () => { const blob = new Blob([exportPlanText(plan)], { type: 'text/plain' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'ocbc-pulse-japan-plan.txt'; a.click(); URL.revokeObjectURL(url) }
  return <div className="animate-view-in space-y-5 px-5 pb-6 pt-2"><header className="flex items-start justify-between pt-2"><div><p className="text-xs font-medium text-primary">FINANCIAL REPORT</p><h1 className="font-heading text-2xl font-extrabold tracking-tight">Japan goal plan</h1><p className="mt-1 text-sm text-muted-foreground">{journey.status === 'approved' ? 'Active plan · approved in OCBC Pulse' : 'Draft plan · ready for your review'}</p></div><button onClick={exportReport} aria-label="Export report" className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-primary-foreground"><Download className="h-4 w-4" /></button></header>
    {!journey.reportGenerated ? <section className="rounded-3xl bg-accent p-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10"><FileText className="h-5 w-5 text-primary" /></span><h2 className="mt-4 font-heading text-xl font-bold">Generate your planning report</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Turn your shared OCBC Pulse journey into a clear timeline, category plan, and next actions.</p><button onClick={generate} className="mt-4 rounded-full bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">Generate Financial Report</button></section> : <><div className="flex gap-1 rounded-2xl bg-secondary p-1">{tabs.map((t) => <button key={t} onClick={() => setTab(t)} className={`flex-1 rounded-xl px-2 py-2 text-[11px] font-semibold ${tab === t ? 'bg-card text-primary shadow-sm' : 'text-muted-foreground'}`}>{t}</button>)}</div>
      {tab === 'Overview' && <><section className="rounded-3xl border border-primary/15 bg-accent p-5"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Pulse summary</p></div><p className="mt-3 text-sm leading-relaxed text-muted-foreground">You are planning to save <b className="text-foreground">{currency(totalContribution(plan))}</b> towards a <b className="text-foreground">{currency(3200)}</b> Japan trip goal. Your current schedule leaves <b className="text-foreground">{currency(remainingGoal(plan))}</b> to refine while protecting monthly cashflow.</p></section><InfoList title="Assumptions" items={planAssumptions} /><section className="rounded-3xl border border-border bg-card p-5"><p className="font-heading font-bold">Recommendation source</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Travel insurance is shown because a broad travel-related transaction was detected and you have an active travel goal. Pulse does not know your destination or itinerary.</p><button onClick={() => onNavigate?.('hub')} className="mt-3 text-sm font-semibold text-primary underline underline-offset-4">Manage Recommendations</button></section><InfoList title="Watch-outs" items={planRisks} /></>}
      {tab === 'Timeline' && <section className="space-y-3">{plan.map((m, i) => <div key={m.month} className="flex gap-3 rounded-2xl border border-border bg-card p-4"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{i + 1}</div><div className="flex-1"><div className="flex justify-between"><p className="font-bold">{m.month}</p><p className="font-semibold text-primary">{currency(m.contribution)}</p></div><p className="mt-1 text-xs text-muted-foreground">Dining {currency(m.categories.dining)} · Shopping {currency(m.categories.shopping)} · Travel {currency(m.categories.travel)}</p></div></div>)}</section>}
      {tab === 'Categories' && <><InfoList title="Category opportunities" items={planOpportunities} /><section className="rounded-3xl border border-border bg-card p-5"><p className="font-heading font-bold">Monthly category guardrails</p>{plan.map((m) => <div key={m.month} className="mt-3 flex items-center justify-between border-b border-border pb-2 text-sm last:border-0"><span>{m.month}</span><span className="text-muted-foreground">{currency(Object.values(m.categories).reduce((a, b) => a + b, 0))} allocated</span></div>)}</section></>}
      {tab === 'Actions' && <section className="space-y-3"><button onClick={exportReport} className="flex w-full items-center gap-3 rounded-2xl border border-border bg-card p-4 text-left"><Download className="h-5 w-5 text-primary" /><span><b className="block text-sm">Export plan</b><span className="text-xs text-muted-foreground">Download a shareable plan file</span></span></button><button onClick={() => setShared(true)} className="flex w-full items-center gap-3 rounded-2xl border border-border bg-card p-4 text-left"><Share2 className="h-5 w-5 text-primary" /><span><b className="block text-sm">{shared ? 'Plan link copied' : 'Share plan'}</b><span className="text-xs text-muted-foreground">Share with a trusted person</span></span></button><button onClick={() => setDiscussed(true)} className="flex w-full items-center gap-3 rounded-2xl border border-border bg-card p-4 text-left"><MessageCircle className="h-5 w-5 text-primary" /><span><b className="block text-sm">{discussed ? 'Discussion started' : 'Discuss with Pulse'}</b><span className="text-xs text-muted-foreground">Continue in the Assistant</span></span></button><button onClick={() => setVariance(!variance)} className="flex w-full items-center gap-3 rounded-2xl border border-border bg-card p-4 text-left"><Target className="h-5 w-5 text-primary" /><span><b className="block text-sm">{variance ? 'Variance tracked' : 'End-of-month variance'}</b><span className="text-xs text-muted-foreground">{variance ? 'Recalibration will be suggested if needed' : 'Track actuals against this plan'}</span></span></button>{onNavigate && <button onClick={() => onNavigate('hub')} className="flex w-full items-center gap-3 rounded-2xl border border-border bg-card p-4 text-left"><Settings2 className="h-5 w-5 text-primary" /><span><b className="block text-sm">Manage Recommendations</b><span className="text-xs text-muted-foreground">Change what Pulse may use and show</span></span></button>}</section>}
    </>}
    {journey.status === 'approved' && <div className="flex items-center gap-2 rounded-2xl bg-[var(--success)]/10 p-3 text-xs font-semibold text-[var(--success)]"><Check className="h-4 w-4" /> Active schedule synced from OCBC Pulse Assistant</div>}</div>
}

function InfoList({ title, items }: { title: string; items: string[] }) { return <section className="rounded-3xl border border-border bg-card p-5"><p className="font-heading font-bold">{title}</p><div className="mt-3 space-y-3">{items.map((item) => <div key={item} className="flex gap-2 text-sm text-muted-foreground"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />{item}</div>)}</div></section> }
