'use client'

import { useState } from 'react'
import Image from 'next/image'
import { AlertTriangle, Check, Edit3, TrendingDown, UtensilsCrossed, Plane, ShoppingBag, Wand2, X } from 'lucide-react'
import { categories, currency } from '@/lib/ocbc-data'
import type { JourneyState } from '@/lib/ocbc-journey'

type Props = { journey: JourneyState; onUpdate: (next: Partial<JourneyState>) => void }
const icons: Record<string, typeof Plane> = { dining: UtensilsCrossed, travel: Plane, shopping: ShoppingBag }

export function SpendingBreakdown({ journey, onUpdate }: Props) {
  const [mode, setMode] = useState<'idle' | 'review' | 'edit'>('idle')
  const [diningCut, setDiningCut] = useState(40)
  const [shoppingCut, setShoppingCut] = useState(40)
  const totalSpent = categories.reduce((s, c) => s + c.spent, 0)
  const apply = () => { onUpdate({ recalibration: 'approved' }); setMode('idle') }
  return <div className="animate-view-in space-y-5 px-5 pb-6 pt-2"><header className="pt-2"><p className="text-xs font-medium text-primary">SPENDING · THIS MONTH</p><h1 className="font-heading text-2xl font-extrabold tracking-tight">Where your money went</h1><p className="mt-1 text-sm text-muted-foreground">You&apos;ve spent <span className="font-bold text-foreground">{currency(totalSpent)}</span> across 3 categories.</p></header>
    <section className={`rounded-3xl border p-5 ${journey.recalibration === 'approved' ? 'border-[var(--success)]/30 bg-[var(--success)]/8' : journey.recalibration === 'rejected' ? 'border-border bg-secondary' : 'border-primary/20 bg-primary/8'}`}><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/15 text-primary">{journey.recalibration === 'approved' ? <Check className="h-4 w-4" /> : journey.recalibration === 'rejected' ? <X className="h-4 w-4" /> : <AlertTriangle className="h-4 w-4" />}</span><p className="text-sm font-bold">{journey.recalibration === 'approved' ? 'Budgets recalibrated' : journey.recalibration === 'rejected' ? 'Recalibration dismissed' : 'AI recalibration needed'}</p></div>
      <p className="mt-3 text-sm leading-relaxed text-muted-foreground">Your <b className="text-foreground">Travel</b> spend is <b className="text-primary">S$80 over</b> target. Pulse can trim Dining and Shopping to absorb it without changing your savings goal.</p>
      {journey.recalibration === 'idle' && mode === 'idle' && <button onClick={() => setMode('review')} className="mt-4 inline-flex items-center gap-2 rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Wand2 className="h-4 w-4" /> Recalibrate Budget</button>}
      {journey.recalibration === 'idle' && mode !== 'idle' && <div className="mt-4 space-y-3"><div className="rounded-2xl bg-card p-3 text-sm"><div className="flex justify-between"><span>Dining trim</span><b>S${diningCut}</b></div><input aria-label="Dining trim" type="range" min="0" max="80" step="10" value={diningCut} onChange={(e) => setDiningCut(Number(e.target.value))} className="mt-2 w-full accent-primary" /><div className="mt-2 flex justify-between"><span>Shopping trim</span><b>S${shoppingCut}</b></div><input aria-label="Shopping trim" type="range" min="0" max="80" step="10" value={shoppingCut} onChange={(e) => setShoppingCut(Number(e.target.value))} className="mt-2 w-full accent-primary" /></div><p className="text-xs text-muted-foreground">Total trim: S${diningCut + shoppingCut}. Need at least S$80.</p><div className="flex gap-2"><button onClick={() => setMode('edit')} className="flex-1 rounded-full border border-border py-2 text-xs font-semibold"><Edit3 className="mr-1 inline h-3 w-3" /> Edit</button><button disabled={diningCut + shoppingCut < 80} onClick={apply} className="flex-1 rounded-full bg-primary py-2 text-xs font-semibold text-primary-foreground disabled:opacity-40">Approve</button><button onClick={() => { onUpdate({ recalibration: 'rejected' }); setMode('idle') }} className="rounded-full border border-border px-3 py-2 text-xs">Reject</button></div></div>}
    </section>
    <section className="space-y-4">{categories.map((c, i) => { const Icon = icons[c.key]; const adjusted = journey.recalibration === 'approved' && c.key !== 'travel' ? c.budget - 40 : c.budget; const over = c.spent > adjusted; const pct = Math.min((c.spent / adjusted) * 100, 100); return <article key={c.key} className="relative overflow-hidden rounded-3xl border border-border bg-card"><div className="relative h-24 w-full"><Image src={c.image || '/placeholder.svg'} alt={c.label} fill sizes="400px" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-black/70 to-black/20" /><div className="absolute inset-0 flex items-center justify-between px-5 text-white"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-white/15"><Icon className="h-5 w-5" /></span><div><p className="font-heading text-base font-bold">{c.label}</p><p className="text-xs text-white/80">{currency(c.spent)} of {currency(adjusted)}</p></div></div>{over ? <span className="rounded-full bg-primary px-2.5 py-1 text-[11px] font-bold">Over</span> : journey.recalibration === 'approved' ? <span className="flex items-center gap-1 rounded-full bg-[var(--success)] px-2.5 py-1 text-[11px] font-bold"><TrendingDown className="h-3 w-3" /> Trimmed</span> : null}</div></div><div className="px-5 py-4"><div className="h-2.5 overflow-hidden rounded-full bg-secondary"><div className={`h-full rounded-full ${over ? 'bg-primary' : 'bg-[var(--success)]'}`} style={{ width: `${pct}%` }} /></div><div className="mt-2 flex justify-between text-xs"><span className="text-muted-foreground">{Math.round(pct)}% used</span><span className={over ? 'font-semibold text-primary' : 'font-semibold'}>{over ? `${currency(c.spent - adjusted)} over` : `${currency(adjusted - c.spent)} left`}</span></div></div></article> })}</section>
  </div>
}
